### ISSUE TITLE
401 unauthorized even the headers are presented

### ISSUE THREAD

**Issue by alihabbash** [lohanidamodar/pdf_viewer#108]
I'm trying to download pdf file  from a url that needs a bearer token but I get unauthorized I tried the same token in swagger and it's successfully done:
What I have done is:
```
    document = await PDFDocument.fromURL(
      widget.title,
      headers: {
        'Authorization' : 'Bearer $accessToken',
      },
    );
```

**Comment by jaasaria** [comment]
@alihabbash got the same error. hope you could share the solution.

**Comment by alihabbash** [comment]
@jaasaria  I actually migrated to another package which was working absolutely fine
https://pub.dev/packages/syncfusion_flutter_pdfviewer
