### ISSUE TITLE
Module not found after iOS build 

### ISSUE THREAD

**Issue by bennyprax** [lohanidamodar/pdf_viewer#54]
I've used this packaged for my iOS app and it works really well. 

I prepared my app for release in iOS with the following steps. 

- [ ] `flutter build ios --release` and it worked!
- [ ] opened it on Xcode and did a build on there but got an error

`Module 'advance_pdf_viewer' not found`

![Screen Shot 2021-06-21 at 22 02 54](https://user-images.githubusercontent.com/13252897/122775157-6f7c7e80-d2dc-11eb-937a-07270123022c.png)

I've tried the following to fix the issue:

- [ ] Clean the build folder in Xcode
- [ ]  Delete the DeriveData
- [ ] ran `flutter clean`

but none of it worked.

**Comment by bennyprax** [comment]
I was able to fix this problem by doing the follow steps:

1. Delete `flutter_advance_pdf_viewer` in pubspec.yaml and comment it from code where it is used
2. Do `flutter build ios --release`
3. Build it in Xcode 
4. Add the package again in pubspec.yaml
5. Uncomment it from the code where it is used
6. Do `flutter build ios --release`
7. Build in Xcode

**Comment by juanagu** [comment]
I fixed it doing this:

```
flutter clean && flutter pub cache repair
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
rm ios/Podfile.lock
flutter build ios
```
